### ISSUE TITLE
Lower the target framework back to netstandard2.0?

### ISSUE THREAD

**Issue by sander1095** [Informatievlaanderen/deterministic-guid-generator#128]
Hello! 

I would love to install this package in a `netstandard2.0` library, but your library requires either `netcoreapp3.1` or `net50`.

I don't really see a reason why. The last supported version for `netstandard2.0` is ` v1.1.1`, and the code doesn't differ a tiny bit compared to the latest version (`v2.2.12`).

Because this is a package that contains a useful utility, I would recommend lowering the framework back to `netstandard2.0` so most projects can make use of it!

For now I can install `v1.1.1`, but that's a suboptimal solution :).

Thanks!

**Comment by ArneD** [comment]
@sander1095 

Version 3.0.1 should have support for `netstandard20`. See: https://www.nuget.org/packages/Be.Vlaanderen.Basisregisters.Generators.Guid.Deterministic/3.0.1
