### ISSUE TITLE
Support netcoreapp3.1

### ISSUE THREAD

**Issue by damianh** [Informatievlaanderen/deterministic-guid-generator#44]
Hi, I've been using this lib in a project and a recent updated dropped support for `netcoreapp3.1` and moved to `net5.0`. So firstly that's a breaking change without a semver major version bump. However, if netcoreapp3.1 were to be added in conjunction with `net5.0` (which shouldn't be a problem since the project has no dependencies) it would not be a breaking change.

If you're not interested in supporting runtimes/frameworks that you don't use... that's cool I'll just ship a fork. 👍🏻

**Comment by CumpsD** [comment]
my mistake @damianh, I'll look into it tomorrow! sometimes it's easy to overlook semver in a big project

**Comment by damianh** [comment]
Cool. Some nice libs/code here :)

**Comment by CumpsD** [comment]
Should be fixed this evening :) after we bump everything to 5.0.2

**Comment by CumpsD** [comment]
@damianh can you try 2.2.11?

**Comment by damianh** [comment]
Works great, cheers @CumpsD !
